### ISSUE TITLE
Tuning support

### ISSUE THREAD

**Issue by lucianoiam** [AudioKit/DunneAudioKit#13]
### Description

Previous versions of the sampler's Swift wrapper offered a `setNoteFrequency()` method  that allowed tuning individual notes. Current versions lack this method thus limiting Swift apps to 12-ET.

### Proposed Solution

Bring back `setNoteFrequency()`. Allow it to work on the fly (ie., without reloading samples).

### Describe Alternatives You've Considered

Write a custom wrapper

**Comment by getdunne** [comment]
I stopped development on this repo a long time ago. Anyone who wishes is welcome to fork it for their own use, but I cannot spare any time to assist.
