### ISSUE TITLE
Add voice changing to Synth()

### ISSUE THREAD

**Issue by NickCulbertson** [AudioKit/DunneAudioKit#20]
### Description

The Synth in DunneAudioKit works great, but it lacks the ability to change the oscillator voices from the Swift side. The voices also can't be changed after initialization.

### Proposed Solution

Allow the user to set and change voices dynamically with AUParameters. 

### Describe Alternatives You've Considered

Create and expose an AUParameter to change voices.

**Comment by getdunne** [comment]
I stopped development on this repo a long time ago. Anyone who wishes is welcome to fork it for their own use, but I cannot spare any time to assist.

**Comment by NickCulbertson** [comment]
I can tell a lot of hard, skilled work went into making this, and I know open-source development is often a thankless job. So thank you sincerely for your work on this, @getdunne!

I think the AudioKit community would like to continue using and updating this package going forward. Would you prefer a new package be created, or can we keep working on this one and change the default reviewer notification settings on GitHub?

Thanks,
Nick

**Comment by getdunne** [comment]
Thanks Nick. I wish I could have kept up my work with AudioKit, but the project I moved on to eats up all my time. By all means continue using this, but please remove me as a reviewer. Even if I had the time, this code has already been changed so much that I no longer recognize it.

-shane
________________________________

**Comment by getdunne** [comment]
Closed; see comments
