### ISSUE TITLE
`unloadAllSamples()` was removed from `Sampler` and causes memory leaks

### ISSUE THREAD

**Issue by christianhengst** [AudioKit/DunneAudioKit#9]
After updating to `>=5.4`, I've noticed that the `unloadAllSamples()` method is not present anymore. Observing the memory usage of my app I've noticed that it increases each time that samples are loaded (via `loadSFZ()`) 

Was this an intended change?

**Comment by aure** [comment]
I believe it was not realtime safe. @wtholliday is that correct? You can bring it back on your own fork of course.

**Comment by wtholliday** [comment]
Yeah we got rid of a bunch of realtime unsafe code. How about helping us out with a decent bug report instead? Closing.
